### PR TITLE
Changed classpath hilt to hilt plugin

### PR DESCRIPTION
**Pull request by Adrc95**
### :tophat: What is the goal?
Remove classpath from hilt and add new syntax via plugin

### :memo: Type of change
 [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by soygabimoreno — APPROVED** [review]
Good catch!

**Review by Monzonprog — APPROVED** [review]
Great!!

**Review by aflopezbec — APPROVED** [review]
Necessary

**Review by RubenGonz2 — APPROVED** [review]

**Review by joancolmenerodev — APPROVED** [review]

**Comment by soygabimoreno** [comment]
Hi, @Adrc95, you are able to merge this PR as soon as you want.

**Pull request merged**
